### ISSUE TITLE
CV: Binston

### ISSUE THREAD

**Issue by binsta** [near/metabuidl-profiles#12]
- __GitHub Profile__: @binsta
- __Available for__: `all`
- __Categories__: `all`
- __Location__: `india:kanniyakumari`
- __Skills__: `near-blockchain`

Looking for team

**Comment by anirudhjust** [comment]
Hey, 
How can I reach you?
Can we discuss our project?

**Comment by binsta** [comment]
> Hey,
> How can I reach you?
> Can we discuss our project?
