### ISSUE TITLE
CV: Illia

### ISSUE THREAD

**Issue by ilblackdragon** [near/metabuidl-profiles#70]
- __GitHub Profile__: @ilblackdragon
- __Available for__: `blockchain-experts`
- __Categories__: `defi` `nft`
- __Location__: `ukraine:kiev`
- __Skills__: `near-blockchain`

Building cool stuff

**Comment by infinity-nft** [comment]
It is very rare to see such a resume in the public domain) I would like to invite you to participate in the craziest hackathon, which is run by a wonderful mood and fresh ideas. And we always have coffee.
